# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "c21a4f3a-d2af-43b6-9545-744a156506d7"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # cocoapods

  # increment_build_number
  # Increment the build number (not the version number)
  # Providing the xcodeproj is optional
  increment_build_number(xcodeproj: "WhatsOpen.xcodeproj")

  # Commit the version bump
  commit_version_bump(xcodeproj: "WhatsOpen.xcodeproj")

  # Add a git tag for this build. This will automatically
  # use an appropriate git tag name
  add_git_tag

  # Push the new commit and tag back to your git remote
  push_to_git_remote

  changelog = prompt(
    text: "Changelog: ",
    multi_line_end_keyword: "END"
  )


  # build your iOS app
  build_app(
    scheme: "WhatsOpen - App Store",
    export_method: "app-store",
    include_bitcode: true
  )



  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  slack(
    slack_url: "https://hooks.slack.com/services/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"
  )
end
