# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
platform :ios, '11.0'
use_frameworks!

def important_pods
  pod 'RealmSwift'

  #pod 'ObjectMapper', '~> 3.2'
  # TEMPORARY BECAUSE Xcode 10
  pod 'ObjectMapper', :git => 'https://github.com/alecdoconnor/ObjectMapper.git', :branch => 'Swift-4.2'
  pod "ObjectMapper+Realm"
end

def ios_pods
  #pod 'Segmentio', '~> 2.1'

  pod 'DeckTransition', '~> 2.0'

  pod 'Fabric'
  pod 'Crashlytics'
end


target 'WhatsOpen' do
  important_pods
  ios_pods
end

target 'WhatsOpen - AppStore' do
  important_pods
  ios_pods
end

target 'WhatsOpenKit' do
  important_pods
end

target 'TodayWidget' do
  important_pods
end

target 'ShortcutsExtension' do
  important_pods
end

target 'ShortcutsExtensionUI' do
  important_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.1'
      end
    
    # From https://twitter.com/nathan
    plist_buddy = "/usr/libexec/PlistBuddy"
    plist = "Pods/Target Support Files/#{target}/Info.plist"
    `#{plist_buddy} -c "Add UIRequiredDeviceCapabilities array" "#{plist}"`
    `#{plist_buddy} -c "Add UIRequiredDeviceCapabilities:0 string arm64" "#{plist}"`
  end
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-WhatsOpen/Pods-WhatsOpen-Acknowledgements.plist', 'WhatsOpen/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

end
